package typescript

import "github.com/codefit-cli/codefit/internal/core/coverage"

// CoverageManifest declares, in plain prose, what codefit audits for TypeScript
// and how — the single source for the human-facing COVERAGE.md and the
// codefit-coverage tool (PRD §10, RF-07). The two categories that split between
// a deterministic rule and mapped surface (ADR 0004) appear in BOTH lists, each
// side describing exactly what it covers, so an evaluator reads a division of
// labor, not a gap.
//
// CoverageManifest is a provider method (not yet on the shared LanguageProvider
// interface) — the interface convergence is deferred until the Go provider also
// emits this (ADR 0003).
func (*Provider) CoverageManifest() coverage.Manifest {
	return coverage.Manifest{
		Language: "typescript",
		Deterministic: []string{
			"Hardcoded secrets: a variable whose NAME looks like a credential (password, apiKey, token, secret, authToken, …) assigned a static string literal. codefit matches by the variable name plus a literal value — it does NOT scan values for the shape of an API key, a private key, or a connection string, so a hardcoded secret that is not tied to a credential-named variable is not caught here.",
			"Weak cryptography: MD5 or SHA-1 hashing — called directly (md5(x), sha1(x)) or via createHash('md5'|'sha1'). These are flagged WHEREVER they appear; a non-security use such as a cache key or an ETag may therefore be a false positive, because deciding whether a hash is security-relevant requires following the data, which is surface. Also flagged: Math.random() assigned to a security-named variable (token, nonce, salt, …), which is not a cryptographically secure source.",
			"Dangerous code evaluation: eval() or new Function() called with a non-constant argument — an identifier, a call, a concatenation, or an interpolated template. A constant string-literal argument is static code and is not flagged.",
			"SQL injection built directly in the database call — a query passed to .query() or .execute() that is assembled inline by string concatenation or by an interpolated template literal, such as db.query(`SELECT ... ${userInput}`). When the query is assembled through an intermediate variable instead, that is surface (below), not here.",
			"Cross-site scripting through React's dangerouslySetInnerHTML when the __html value is built inline — by concatenation or by an interpolated template. When __html is set from a plain variable, its safety depends on earlier sanitization, which is surface (below), not here; a constant __html is not flagged.",
			"Database structure — table without a primary key (DB-050): a model with no @id and no @@id. A table with no primary key is a structurally undeniable defect, so it is affirmed deterministically. Read from the configured schema — a Prisma schema.prisma OR a directory of SQL-DDL (Flyway PostgreSQL) migrations reconstructed to their final state (database.schema_paths); the DB dimension covers only what the schema states, not query behavior. NOTE (scalability): the DB rules are language-neutral (they reason over the neutral schema model, not TypeScript), so this DB coverage prose is duplicated per-provider today; it should move to a neutral DB-coverage source when a second ORM provider lands.",
		},
		Reasoning: []string{
			"SQL injection where the query is assembled in steps through intermediate variables (for example: const q = \"...\" + input; db.query(q)) — codefit maps the database calls as surface so the agent can reason about where the query text came from.",
			"Cross-site scripting where dangerouslySetInnerHTML receives a variable whose safety depends on whether it was sanitized earlier — codefit maps these so the agent can judge whether the value is safe.",
			"IDOR: Next.js App Router route handlers AND Next.js Server Actions ('use server') that receive a client-controlled identifier and reach a resource — mapped so the agent verifies ownership is checked. For a route handler the id-input is read from the request (route param, query string, or request body); for a Server Action it arrives as the function's arguments (or a FormData), since an action is a POST endpoint whose input IS its arguments. Server Actions are detected by SHAPE — an async function under a 'use server' directive at file level (every exported async function) or at function level (an inline action in a Server Component, or a non-exported one) — never by filename, so an action in actions.ts, lib/, or inline is not a blind spot (ADR 0005). An object-shaped argument is covered: the parameter binding is seeded as the id-var, so a nested data.id flows to the access. codefit enumerates the id-input and the local Prisma access deterministically; when the id leaves the body (passed to a service/repository call), it is still enumerated with an honest signal saying the access may be indirect, and the agent follows the data. An id reached only after several intermediate revalidation steps may not be linked to its access — that deeper data-follow is the agent's, declared here (ADR 0005). id-input is matched by structure, not by name, so a filter query param or a non-id action argument (date, limit) may be over-enumerated; the signal names what it read so the agent dismisses it at a glance — this noise is accepted to avoid a name-based blind spot for non-standard id names (ADR 0005). Each item carries the queryable structural facts local_access_detected (true = a Prisma access is in the body; false = the id leaves the body to a service/repository, the frontier) and server_action (true = the entry is a Server Action, not a route handler) — facts, not judgments. IDOR is about resource OWNERSHIP, which codefit cannot verify from structure, so an IDOR with a local access stays ACTIONABLE even when an authz helper is present: a known/registered helper proves authentication/permission, not that the caller owns this resource (ADR 0006 amended; ADR 0013). known_authz_detected gates the authz concern, never the IDOR one.",
			"Broken authorization: Next.js App Router route handlers AND Server Actions that perform a sensitive operation — they touch data or mutate state (a Prisma read or write, or an indirect service/repository call) — mapped with a signal stating the operation and whether a known authorization helper was detected in the body, so the agent verifies the caller is permitted. This is broader than IDOR: it needs no client id, only a sensitive operation, so it enumerates more entries (a deliberate trade — an entry that does something sensitive is worth a glance even if no check is missing). A Server Action that mutates or reads with no detected authz helper is exactly the case worth surfacing — actions are POST endpoints developers often do not guard like endpoints. It is matched by the structural operation, never by route name (an endpoint without 'admin' in its path may still need authorization — ADR 0005). The indirect/service case and deep data-follow are the agent's, declared as for IDOR. Each item carries a queryable structural fact, known_authz_detected, the boolean form of the prose signal; consumers may order by it (unchecked first) but it is a FACT (a known pattern was/wasn't seen), not a severity — known_authz_detected=false means 'no known authz pattern was detected here', never 'this is unauthorized'. The recognized helper set is the built-in NextAuth-style names PLUS the project's own helpers, which the agent identifies by reasoning over the code and a human approves registering via codefit-baseline-register-authz-helper; codefit persists them in the committed baseline and recognizes them on later scans without the agent re-reasoning (ADR 0013). Registering a helper clears the AUTHZ gap (permission), never the IDOR/ownership gap.",
			"Over-fetching of sensitive data: points where a domain object is serialized from a Prisma find — for a route handler the serialization sink is an explicit Response.json / NextResponse.json / JSON.stringify; for a Server Action it is the RETURN value, which the framework serializes to the client (an action has no Response.json). Mapped with a queryable structural fact, field_limiting_detected (true = the find has a select/omit clause; false = no clause, so all columns are returned). codefit does NOT judge whether the exposed fields are sensitive — it does not know that passwordHash is sensitive and name is not; that requires the domain/schema and is the agent's. codefit gives the structural fact (a full model serialized without select); the agent reads the schema and judges sensitivity. Serialization from a service/repository instead of an inline find is the frontier (codefit cannot see the find's field selection) — enumerated with an honest signal for the agent to follow. Matched by the structural serialization, never by model name (an unfamiliar model may still over-expose — ADR 0005). The tool orders by structural certainty using the queryable facts local_access_detected and field_limiting_detected — a local find with no select first (confirmed), the frontier last (present, honest) — without filtering anything; the frontier is never dropped, because filtering it would reintroduce a shape-based blind spot (ADR 0005).",
			"Express and Fastify route handlers: the same IDOR, broken-authorization, and over-fetching surface above is mapped for these non-Next.js frameworks. Handlers are discovered by SHAPE, never by path — an Express router/app `.get|.post|.put|.patch|.delete('/path', ...middleware, handler)` call, and Fastify's options-object form `.get('/path', { handler, preHandler })` — so a same-named non-route call (map.get('/k', v), arr.get(0, cb)) is not mistaken for a route: a handler requires a string-literal path AND an inline function. The client id-input is read from req.params/req.query/req.body (Express) or request.params/query/body (Fastify), keyed off the handler's FIRST parameter (its name is the developer's, not assumed to be `req`), so a non-standard route param like `slug` is not a blind spot. The over-fetching sink is the response object's .json()/.send() (Express res, Fastify reply), keyed off the SECOND parameter. The authorization guard in these frameworks is route MIDDLEWARE, not a body call: codefit reads Express positional middleware (router.post('/x', auth.required, handler)) and Fastify preHandler/onRequest hooks, so known_authz_detected reflects a guard applied at the route, and the signal states honestly whether it looked in the body or also the route middleware. When the resource access or sensitive operation is NOT local to the handler body — the id is passed to a service/repository in another file (the common controller→service split) — codefit emits the queryable fact indirect_access=true and names the callee in indirect_call; it does NOT follow the call across files (cross-file option C), the agent reasons over the named function. Detection is by shape, so an id-input or sink that is structurally present but semantically irrelevant may be over-enumerated; the signal names what it read so the agent dismisses it at a glance.",
			"NestJS controllers: the same IDOR, broken-authorization, and over-fetching surface is mapped for NestJS, whose routes are class methods declared with DECORATORS. A handler is a method carrying an HTTP-verb decorator (@Get/@Post/@Put/@Patch/@Delete/...), detected by that shape — never by @Controller (a class without it can still expose routes — ADR 0005). The client id-input is read from the method's PARAMETER decorators (@Param('id'), @Query(), @Body()), each bound to an id-var the downstream follows; a framework @User-style injected param (the authenticated principal) is NOT treated as a resource id. The authorization guard is the @UseGuards decorator on the method or inherited from the class — detected by PRESENCE (the decorator IS the guard mechanism; guard class names are arbitrary, so codefit names the guard but does not match it against a known set), and a class-level guard applies to every method. The over-fetching sink is the RETURN value, which NestJS serializes to the client (like a Server Action — there is no res.json). When the resource access or sensitive operation lives in an injected service in another file (this.someService.method(...), the common controller→service split), codefit emits indirect_access=true and names the callee — it does not follow the call across files (option C). Known limits: a service method whose name collides with a Prisma method (create/update/delete/findMany/...) is reported as a LOCAL Prisma access rather than an indirect call (the Prisma-by-shape match above) — still surfaced for review with the real callee named; a handler that returns through an explicit @Res() response object is not mapped. Guard detection sees @UseGuards (method- and class-level) ONLY — NestJS authentication applied as module-bound middleware (consumer.apply(AuthMiddleware) in a module's configure()) or as a global guard (APP_GUARD provider / app.useGlobalGuards) is NOT detected, so on apps that guard via middleware rather than @UseGuards, known_authz_detected reads false across the board (a conservative 'verify', never a false 'secure').",
			"Database structure from the schema, mapped as surface for the agent to reason (read from database.schema_paths; schema-only, no query analysis): foreign keys with no covering index (DB-001) — a FK is covered when some index's leading columns match it (the primary key counts as an implicit index, a @unique as an index); whether an un-indexed FK matters depends on the table's size and access pattern, so codefit states the fact (fk_columns, existing_indexes, covering_index_detected=false) and the agent judges. Exact duplicate indexes (DB-011) — two indexes on the same columns in the same order with the same uniqueness; which to drop is the human's call. Multivalued (array) columns (DB-002) — an array violates 1NF, but a native array (Postgres) is legitimate sometimes, so it is surfaced not affirmed. Prefix-redundant indexes ([a] subsumed by [a,b]) are NOT yet detected — a known gap for a later slice.",
			"Database structure — name-heuristic checks, mapped as surface (schema-only). These read meaning from column names, which is inherently noisy, so they are NEVER affirmed: codefit states the structural fact and the agent judges. (1) Foreign key typed as text (DB-051): a String/Text FK whose referenced key is numeric, or an unbounded @db.Text key — a String FK to a String uuid/cuid key does NOT fire (it is a structural type-mismatch check, not a name guess), and an unresolvable reference does not fire. Facts: type_mismatch, text_key, referenced_type_resolved. (2) Missing audit timestamps (DB-052): a table with NEITHER createdAt NOR updatedAt; looks_like_join_table is exposed so link tables can be dismissed. Only-one-missing is a deferred candidate, not fired yet. (3) Sensitive column stored in the clear (DB-053): a column whose name matches a sensitive token (password, token, apiKey, ssn, …) and whose type holds a value (String/Text/Bytes). It ALWAYS emits; an encryption hint in the name (passwordHash, encrypted…) is reported as the fact encryption_hint_in_name, NOT used to suppress — a name is not a guarantee, and hiding a possible plaintext secret would be a silent false negative. Names are matched by component (camelCase/snake_case), never raw substring, so passwordChangedAt (a DateTime) and passwordResetCount (an Int) do not fire. (4) Repeating groups (DB-003): two or more same-typed columns sharing a base name with numeric suffixes (phone1/phone2/phone3) — a 1NF smell the agent weighs against an intentional fixed set (address line 1/2).",
		},
		NotCovered: []string{
			"Race conditions in business logic.",
			"Architectural design flaws.",
			"Business-logic correctness (this is not a security property).",
			"Deep static taint analysis — covered by surface mapping plus agent reasoning, not deterministically.",
			"JavaScript server frameworks beyond Next.js, Express, Fastify, and NestJS: not yet covered — a known gap, not a silent one.",
			"An Express/Fastify route handler passed by REFERENCE — a named identifier rather than an inline function (router.get('/x', listUsers), where listUsers is defined elsewhere) — is not enumerated: codefit maps inline handler bodies, and a handler whose body lives in another scope is a cross-file case the agent must follow. (An auth GUARD by reference is unaffected: it is matched by name in the registration, so a known/registered guard still sets known_authz_detected without codefit reading its body.)",
			"Server Action input read inline from a FormData (formData.get('key')) and passed DIRECTLY into a service call, with no intermediate variable and no local Prisma access, may not link to that indirect access; when bound to a variable first, it links. The local-access case always enumerates.",
			"Database query behaviour: N+1 access patterns and index-vs-query analysis (whether an existing index serves the queries the code actually runs) are NOT covered — the DB dimension is schema-only, it does not read the application's queries.",
			"Database views, stored procedures/functions, and triggers (DB-020..041): the SQL-DDL parser records their names, but codefit has NO rules auditing them yet — a known gap, not a silent one.",
			"OLAP / data-warehouse schemas (star/snowflake models, slowly-changing dimensions, columnar/partitioning concerns): out of scope; the DB dimension audits OLTP structure only.",
		},
	}
}
