package dbcoverage

// Deterministic returns the DB dimension's deterministic coverage prose — the
// classes the DB rules affirm with certainty 1.0.
func Deterministic() []string {
	return []string{
		"Database structure — table without a primary key (DB-050): a model with no @id and no @@id. A table with no primary key is a structurally undeniable defect, so it is affirmed deterministically. Read from the configured schema — a Prisma schema.prisma OR a directory of SQL-DDL (Flyway) migrations reconstructed to their final state (database.schema_paths). SQL-DDL parsing supports THREE dialects — PostgreSQL, MySQL, and SQL Server (T-SQL) — selected by the `database.type` setting in .codefit.yaml (postgresql | mysql | sqlserver); `sqlite` is recognized but returns an explicit \"not supported yet\" note rather than silently parsing as Postgres. All DB rules (DB-050 and below) are dialect-agnostic: they reason over the neutral db.Schema model reconstructed by whichever dialect parsed the DDL, never over dialect-specific fields, so the same rule set runs identically regardless of dialect. An unmapped type keyword in the source DDL (one the dialect's type vocabulary does not recognize) falls back to db.TypeUnknown — an honest fallback, never a silent guess. The DB dimension covers only what the schema states, not query behavior.",
	}
}

// Reasoning returns the DB dimension's coverage prose mapped as surface for the
// agent to reason over — schema-only structural facts codefit does not affirm.
func Reasoning() []string {
	return []string{
		"Database structure from the schema, mapped as surface for the agent to reason (read from database.schema_paths; schema-only, no query analysis): foreign keys with no covering index (DB-001) — a FK is covered when some index's leading columns match it (the primary key counts as an implicit index, a @unique as an index); whether an un-indexed FK matters depends on the table's size and access pattern, so codefit states the fact (fk_columns, existing_indexes, covering_index_detected=false) and the agent judges. Exact duplicate indexes (DB-011a) — two indexes on the same columns in the same order with the same uniqueness; which to drop is the human's call. Real-world coverage is dialect-uneven: on PostgreSQL/Pagila this rule fires on a GENUINE upstream duplicate (the payment_p2022_01 partition ships both idx_fk_payment_p2022_01_customer_id and payment_p2022_01_customer_id_idx on the identical column) — the only one of the three dialects where the positive case is proven by real vendored DDL rather than a constructed one; on MySQL/Sakila and SQL Server/AdventureWorks the rule is verified CLEAN against real DDL (no false positives), but its positive fire path is proven only by a constructed (synthetic) schema, since neither real corpus happens to ship a duplicate index. Multivalued (array) columns (DB-002) — an array violates 1NF, but a native array (Postgres) is legitimate sometimes, so it is surfaced not affirmed.",
		"Prefix-redundant indexes (DB-011b, Phase 2.2) — an index [a] that is a STRICT leading prefix of a wider index-like coverer [a,b] on the same table (a real index, or the primary key treated as an implicit index) is pure write/storage overhead, since the wider one already serves any lookup the narrower one would; which to drop is the human's call, so this is surface, never an affirmation. A UNIQUE index never fires (it enforces a uniqueness constraint the wider composite does not guarantee for its own leading columns alone). Supported on all three dialects — PostgreSQL/Pagila, MySQL/Sakila, and SQL Server/AdventureWorks all run CLEAN against their real vendored DDL (none of the three real corpora happens to contain a genuine prefix-redundant pair, a real honest finding about how these schemas are actually indexed, not a rule gap); the positive fire path on every dialect is proven by mutating a copy of a real table (e.g. adding a synthetic index on the leading column of Sakila's own real film_actor composite primary key [actor_id, film_id]), never by a fully synthetic fixture.",
		"Database structure — name-heuristic checks, mapped as surface (schema-only). These read meaning from column names, which is inherently noisy, so they are NEVER affirmed: codefit states the structural fact and the agent judges. (1) Foreign key typed as text (DB-051): a String/Text FK whose referenced key is numeric, or an unbounded @db.Text key — a String FK to a String uuid/cuid key does NOT fire (it is a structural type-mismatch check, not a name guess), and an unresolvable reference does not fire. Facts: type_mismatch, text_key, referenced_type_resolved. (2) Missing audit timestamps (DB-052): a table with NEITHER createdAt NOR updatedAt; looks_like_join_table is exposed so link tables can be dismissed. Only-one-missing is a deferred candidate, not fired yet. (3) Sensitive column stored in the clear (DB-053): a column whose name matches a sensitive token (password, token, apiKey, ssn, …) and whose type holds a value (String/Text/Bytes). It ALWAYS emits; an encryption hint in the name (passwordHash, encrypted…) is reported as the fact encryption_hint_in_name, NOT used to suppress — a name is not a guarantee, and hiding a possible plaintext secret would be a silent false negative. Names are matched by component (camelCase/snake_case), never raw substring, so passwordChangedAt (a DateTime) and passwordResetCount (an Int) do not fire. (4) Repeating groups (DB-003): two or more same-typed columns sharing a base name with numeric suffixes (phone1/phone2/phone3) — a 1NF smell the agent weighs against an intentional fixed set (address line 1/2).",
		"View sensitive-column exposure (DB-020, Phase 2.2) — a VIEW whose top-level SELECT column list exposes a column or alias whose name matches a sensitive token (the same vocabulary DB-053 uses). Reads the view's captured body text through a deliberately bounded SELECT-projection scanner, never a general SQL-expression parser: a function call, CASE expression, or subquery item with no alias is a declared miss for that one item, and SELECT * is a declared miss for the whole view (the column list is not literal in the DDL text). Never an affirmation — a column named password in a view says nothing about whether the underlying value is masked, hashed, or genuinely exposed to whoever queries the view, so this is always surface. Runs CLEAN on real DDL across all three dialects: Pagila's actor_info, AdventureWorks' vEmployee, and Sakila's customer_list all legitimately confirm the negative case (a real, well-designed view's whole purpose is usually a curated projection, so it rarely re-exposes a raw sensitive column under a sensitive-looking name — a real finding about how views are written, not a gap in the rule). The POSITIVE fire path is proven ONLY by a CONSTRUCTED case: renaming the real, vendored Sakila customer_list view's own trailing \"AS SID\" alias to \"AS ssn\". No real view in any of the three dogfooded corpora genuinely exposes a sensitive-named column — that is stated plainly, not implied by the negative runs above. Zero value on Prisma-only projects: Prisma's schema.prisma has no view-block concept (ADR 0014 places it out of scope), so a Prisma-only project has no views for this rule to read at all.",
	}
}

// NotCovered returns the DB dimension's explicit gaps: what codefit does not
// audit for this dimension, stated plainly rather than left silent.
func NotCovered() []string {
	return []string{
		"Index-vs-query analysis — whether an existing index actually serves the queries the application code runs — is NOT covered: the DB dimension is schema-only, it does not read query text or application code. (N+1 query-in-loop patterns are a DIFFERENT capability and are NO LONGER part of this gap: N+1 is mapped as per-handler surface by the language provider, not by the schema-only DB dimension, so it appears in scan-all's endpoint buckets, never in this DB section.)",
		"Never-used index (DB-012) is NOT covered, and this is PERMANENT, not deferred: detecting an unused index requires runtime query telemetry (e.g. PostgreSQL's pg_stat_user_indexes) that only exists inside a live, running database with real traffic history. codefit's model is static and never connects to a database — it reads only DDL/schema text — so this rule is structurally incompatible with how codefit operates, not merely unscheduled.",
		"Database views ARE covered for one rule (DB-020, sensitive-column exposure — see Reasoning, above). Stored procedures/functions and triggers (DB-030 dynamic SQL by string concatenation, DB-031 missing exception handling, DB-040 trigger cross-table DML, DB-041 trigger external-effecting call) are NOT covered in this release — the SQL-DDL parser records their names and, where the dialect allows, their bodies, but no rule reads them yet. This is DEFERRED, not abandoned: it moves to a separate change (routine-body-rules, a later slice of 0.2.3). The parser prerequisite is now DONE — a multi-statement T-SQL routine body is captured COMPLETE to the GO batch separator (or EOF), NOT truncated at its first internal ';' (ADR 0027; PostgreSQL dollar-quoted and MySQL DELIMITER-wrapped bodies were already complete). So the blocker is lifted and the full body text is available marked Complete; what remains is simply that the four rules are not implemented yet — no longer a parser gap. (Had they shipped over the OLD truncated T-SQL body, a rule like DB-031 \"is exception handling present?\" would have FALSELY AFFIRMED an absence that was really just unread text past the cut — which is exactly why the parser fix came first.) When the routine-body rules land, they will carry the same Prisma-zero-value limit as DB-020: Prisma's schema.prisma has no stored-procedure/trigger block concept, so a Prisma-only project gets no value from this rule family either.",
		"OLAP / data-warehouse schemas (star/snowflake models, slowly-changing dimensions, columnar/partitioning concerns): out of scope; the DB dimension audits OLTP structure only.",
		"SQL-DDL dialect known limits (declared, not silent): (1) a T-SQL routine body is captured to the GO batch separator (or EOF), so a CREATE TABLE-shaped fragment inside a GO-batched procedure/trigger body is absorbed into the body, NOT surfaced as a spurious top-level table (ADR 0027, closing a limit ADR 0022 had declared); the trade is that a T-SQL routine with NO trailing GO immediately followed by another statement absorbs that statement into the body — invalid T-SQL batching, the intentional boundary of ADR 0027. MySQL routine bodies wrapped in DELIMITER //...// are unaffected. (2) A MySQL client DELIMITER directive is recognized only when its argument is punctuation (//, $$); a word-based delimiter such as DELIMITER GO is NOT recognized. (3) The T-SQL GO batch separator is recognized only when a line is exactly \"GO\"; a column literally named go alone on its own line would collide (vanishingly rare, accepted). (4) An inline index whose NAME is itself a type keyword (e.g. KEY int (col), an index named \"int\") is read as a column — the KEY/INDEX-vs-column discriminator trusts a type-named token as a column (pathological, accepted). (5) A column named exactly key, index, fulltext, or spatial whose type is NOT in the dialect's recognized type vocabulary (e.g. PostgreSQL's tsvector, as in real Pagila's film.fulltext column) collides with the SAME inline-index-shorthand heuristic from a different direction: the column is silently dropped and a phantom zero-column index is fabricated in its place instead. Confirmed against real vendored Pagila DDL; not yet fixed.",
		"SQL-DDL dialect assumptions: MySQL parsing assumes ANSI_QUOTES is OFF (a bare \" is read as a string literal, not an identifier quote); the parser binds a single dialect per project at construction (a project mixing dialects is not supported). A project mixing .prisma and .sql schema inputs is likewise out of scope.",
	}
}
