package dbrules

import "testing"

// identityVerdict is one frozen (name -> token, ok) verdict.
type identityVerdict struct {
	name  string
	token string
	ok    bool
}

// identityGolden is the EXACT output of matchSensitiveToken at main 0fb211d,
// measured by running the pre-extraction implementation over identityCorpus and
// transcribing what it printed. It is a literal HERE, in the test, on purpose:
// a golden generated by calling the implementation would compare production to
// production and prove nothing.
//
// Read the order-adversarial rows carefully, because they are the whole point:
//
//	ssnPassword     -> "ssn"       (not "password")
//	passwordSsn     -> "password"  (not "ssn")
//	apiKeyCvv       -> "cvv"       (not "apikey" — a single component outranks
//	                                the api+key PAIR, because every component is
//	                                scanned before any pair is)
//	cardNumberToken -> "token"     (not "cardnumber", same reason)
//
// A credential-first two-pass returns different tokens for all four while
// returning the same booleans. The token is EVIDENCE — it reaches the user
// inside DB-053's and DB-020's messages — so a control that compared only the
// boolean would pass while the message silently changed.
var identityGolden = []identityVerdict{
	{"accessToken", "token", true},
	{"aId", "", false},
	{"api", "", false},
	{"apiKey", "apikey", true},
	{"api_key", "apikey", true},
	{"at", "", false},
	{"authorId", "", false},
	{"bId", "", false},
	{"bio", "", false},
	{"changed", "", false},
	{"code1", "", false},
	{"code2", "", false},
	{"count", "", false},
	{"createdAt", "", false},
	{"created_at", "", false},
	{"creditCard", "creditcard", true},
	{"description", "", false},
	{"digest", "", false},
	{"encryptedSecret", "secret", true},
	{"ghostId", "", false},
	{"id", "", false},
	{"isPublic", "", false},
	{"key", "", false},
	{"keyboard", "", false},
	{"name", "", false},
	{"orgId", "", false},
	{"orgRef", "", false},
	{"password", "password", true},
	{"passwordChangedAt", "password", true},
	{"passwordHash", "password", true},
	{"passwordResetCount", "password", true},
	{"password_reset", "password", true},
	{"phone", "", false},
	{"phone1", "", false},
	{"phone2", "", false},
	{"phone3", "", false},
	{"postId", "", false},
	{"refresh", "", false},
	{"refreshToken", "token", true},
	{"reset", "", false},
	{"secret", "secret", true},
	{"sequence", "", false},
	{"ssn", "ssn", true},
	{"SSN", "ssn", true},
	{"text_key", "", false},
	{"token", "token", true},
	{"tokenHashed", "token", true},
	{"updatedAt", "", false},
	{"updated_at", "", false},
	{"dim_contact", "", false},
	{"v_secrets", "", false},
	{"v_tokens", "", false},
	{"Contact", "", false},
	{"Child", "", false},
	{"Ghost", "", false},
	{"Link", "", false},
	{"Org", "", false},
	{"Post", "", false},
	{"User", "", false},
	{"passwd", "passwd", true},
	{"pwd", "pwd", true},
	{"apikey", "apikey", true},
	{"accesstoken", "accesstoken", true},
	{"refreshtoken", "refreshtoken", true},
	{"privatekey", "privatekey", true},
	{"dni", "dni", true},
	{"creditcard", "creditcard", true},
	{"cardnumber", "cardnumber", true},
	{"cvv", "cvv", true},
	{"cvc", "cvc", true},
	{"ssnPassword", "ssn", true},
	{"passwordSsn", "password", true},
	{"apiKeyCvv", "cvv", true},
	{"cardNumberToken", "token", true},
	{"refreshTokenSsn", "token", true},
	{"API_KEY", "apikey", true},
	{"accessKey", "", false},
	{"SIGNING_KEY", "", false},
	{"privateKey", "privatekey", true},
	{"encryptionKey", "", false},
	{"secretkey", "", false},
	{"tokenizer", "", false},
	{"monkeyIndex", "", false},
	{"publicKey", "", false},
}

// TestMatchSensitiveTokenIdentity is the extraction's proof, not its
// description. DB-053 is load-bearing across 29 measured corpora (ADR 0047)
// whose corpora are no longer cloned, so "it still compiles" and "the existing
// tests pass" are both too weak: the existing tests assert booleans over eight
// names and would not notice the returned token changing on any of them.
func TestMatchSensitiveTokenIdentity(t *testing.T) {
	if len(identityGolden) != len(identityCorpus) {
		t.Fatalf("golden has %d rows for a corpus of %d names — one was edited without the other",
			len(identityGolden), len(identityCorpus))
	}
	for i, want := range identityGolden {
		if want.name != identityCorpus[i] {
			t.Fatalf("row %d: golden name %q does not line up with corpus name %q",
				i, want.name, identityCorpus[i])
		}
		tok, ok := matchSensitiveToken(want.name)
		if tok != want.token || ok != want.ok {
			t.Errorf("matchSensitiveToken(%q) = (%q, %v), frozen golden says (%q, %v)",
				want.name, tok, ok, want.token, want.ok)
		}
	}

	// Positive control on the golden itself. A golden of all-false rows would
	// be satisfied by a matcher that never matches anything.
	var matched int
	for _, g := range identityGolden {
		if g.ok {
			matched++
		}
	}
	if matched < 30 {
		t.Fatalf("golden asserts only %d matches — too few to prove the matcher matches", matched)
	}
}

// identityCorpus is the input set the DB-053 extraction is proven identical
// over. It is deliberately wider than "names that match":
//
//   - every column/table name appearing in DB-053's and DB-020's fixtures (both
//     rules consume matchSensitiveToken), so the corpus is grounded in what the
//     rules actually see rather than in what a vocabulary list suggests;
//   - all 15 entries of the vocabulary itself, so no entry can be dropped
//     silently;
//   - ORDER-ADVERSARIAL names carrying two vocabulary tokens in both orders
//     (ssnPassword / passwordSsn, apiKeyCvv, cardNumberToken, refreshTokenSsn).
//     These exist because the matched token is EVIDENCE that reaches the user:
//     the scan order (all components in order, THEN all adjacent pairs, over one
//     union) makes ssnPassword return "ssn". A credential-first two-pass returns
//     "password" — the same boolean with different evidence, which a control
//     comparing only the verdict would pass by vacuum;
//   - credential spellings SEC-001 cares about (API_KEY, accessKey, privateKey,
//     SIGNING_KEY, encryptionKey, secretkey, tokenizer). DB-053's verdict on
//     these must NOT move just because SEC-001's vocabulary grew — that is the
//     whole point of keeping the sets separate and unioning only for DB-053.
var identityCorpus = []string{
	// DB-053 / DB-020 fixture names.
	"accessToken", "aId", "api", "apiKey", "api_key", "at", "authorId", "bId",
	"bio", "changed", "code1", "code2", "count", "createdAt", "created_at",
	"creditCard", "description", "digest", "encryptedSecret", "ghostId", "id",
	"isPublic", "key", "keyboard", "name", "orgId", "orgRef", "password",
	"passwordChangedAt", "passwordHash", "passwordResetCount", "password_reset",
	"phone", "phone1", "phone2", "phone3", "postId", "refresh", "refreshToken",
	"reset", "secret", "sequence", "ssn", "SSN", "text_key", "token",
	"tokenHashed", "updatedAt", "updated_at", "dim_contact", "v_secrets",
	"v_tokens", "Contact", "Child", "Ghost", "Link", "Org", "Post", "User",
	// The vocabulary's own 15 entries.
	"passwd", "pwd", "apikey", "accesstoken", "refreshtoken", "privatekey",
	"dni", "creditcard", "cardnumber", "cvv", "cvc",
	// Order-adversarial: two vocabulary tokens, both orders.
	"ssnPassword", "passwordSsn", "apiKeyCvv", "cardNumberToken", "refreshTokenSsn",
	// SEC-001 spellings, pinned so DB-053 cannot drift with SEC-001's set.
	"API_KEY", "accessKey", "SIGNING_KEY", "privateKey", "encryptionKey",
	"secretkey", "tokenizer", "monkeyIndex", "publicKey",
}
