package scaffold

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// yamlScalar renders s as a YAML-safe scalar (correctly quoted/escaped for any
// content — a project name with quotes, backslashes, colons, …). The config name
// is free text (the project dir), so it must never be interpolated raw, or a
// hostile/odd dir name would produce an unloadable config reported as success.
func yamlScalar(s string) string {
	out, err := yaml.Marshal(s)
	if err != nil {
		return `""` // unreachable for strings; stay valid YAML if it ever happens
	}
	return strings.TrimRight(string(out), "\n")
}

var configFuncs = template.FuncMap{"q": yamlScalar}

// configTemplate renders a commented .codefit.yaml from a ProjectInfo. It is a
// commented template (not yaml.Marshal of the Config struct, which would dump
// every zero-value field): the file is committed and human-edited, so it stays
// minimal and readable. Sections not detected (database) are omitted; config
// loading fills the rest with defaults.
//
// Only fields within config's validated enums are ever emitted, so the output
// always round-trips through config.Load.
var configTemplate = template.Must(template.New("config").Funcs(configFuncs).Parse(
	`# .codefit.yaml — project config for codefit, the AI-generated-code auditor.
# Committed and shared, like .eslintrc. Generated by ` + "`codefit init`" + `; edit freely.
version: "1"

project:
  name: {{q .Name}}
  language: {{q .Language}}
{{- if .Framework}}
  framework: {{q .Framework}}
{{- end}}
  # path_criticality weights finding severity by location: a secret in a test is
  # noise; in production it is critical. Globs are project-relative.
  path_criticality:
    production:
{{- range .Production}}
      - {{q .}}
{{- end}}
{{- if .Test}}
    test:
{{- range .Test}}
      - {{q .}}
{{- end}}
{{- end}}
{{- if .Example}}
    example:
{{- range .Example}}
      - {{q .}}
{{- end}}
{{- end}}
{{- if .ORM}}

database:
  orm: {{q .ORM}}
{{- if .DBType}}
  type: {{q .DBType}}
{{- end}}
{{- if .DBParadigm}}
  paradigm: {{q .DBParadigm}}
{{- end}}
{{- if .SchemaPaths}}
  schema_paths:
{{- range .SchemaPaths}}
    - {{q .}}
{{- end}}
{{- end}}
{{- end}}
`))

// configView is the flattened, slash-normalized data the config template needs.
type configView struct {
	Name, Language, Framework string
	Production, Test, Example []string
	ORM, DBType, DBParadigm   string
	SchemaPaths               []string
}

// RenderConfig renders a commented .codefit.yaml for the detected project. Paths
// are slash-normalized so the committed file is portable across operating systems.
func RenderConfig(info ProjectInfo) ([]byte, error) {
	view := configView{
		Name:        info.Name,
		Language:    info.Language,
		Framework:   info.Framework,
		Production:  toSlashAll(info.PathCriticality.Production),
		Test:        toSlashAll(info.PathCriticality.Test),
		Example:     toSlashAll(info.PathCriticality.Example),
		ORM:         info.ORM,
		DBType:      info.DBType,
		DBParadigm:  info.DBParadigm,
		SchemaPaths: toSlashAll(info.SchemaPaths),
	}
	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, view); err != nil {
		return nil, fmt.Errorf("rendering config: %w", err)
	}
	return buf.Bytes(), nil
}

func toSlashAll(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := make([]string, len(in))
	for i, s := range in {
		out[i] = filepath.ToSlash(s)
	}
	return out
}
