package scaffold

import (
	"bytes"
	"fmt"
	"path/filepath"
	"text/template"
)

// configTemplate renders a commented .codefit.yaml from a ProjectInfo. It is a
// commented template (not yaml.Marshal of the Config struct, which would dump
// every zero-value field): the file is committed and human-edited, so it stays
// minimal and readable. Sections not detected (database) are omitted; config
// loading fills the rest with defaults.
//
// Only fields within config's validated enums are ever emitted, so the output
// always round-trips through config.Load.
var configTemplate = template.Must(template.New("config").Parse(
	`# .codefit.yaml — project config for codefit, the AI-generated-code auditor.
# Committed and shared, like .eslintrc. Generated by ` + "`codefit init`" + `; edit freely.
version: "1"

project:
  name: "{{.Name}}"
  language: "{{.Language}}"
{{- if .Framework}}
  framework: "{{.Framework}}"
{{- end}}
  # path_criticality weights finding severity by location: a secret in a test is
  # noise; in production it is critical. Globs are project-relative.
  path_criticality:
    production:
{{- range .Production}}
      - "{{.}}"
{{- end}}
{{- if .Test}}
    test:
{{- range .Test}}
      - "{{.}}"
{{- end}}
{{- end}}
{{- if .Example}}
    example:
{{- range .Example}}
      - "{{.}}"
{{- end}}
{{- end}}
{{- if .ORM}}

database:
  orm: "{{.ORM}}"
{{- if .DBType}}
  type: "{{.DBType}}"
{{- end}}
{{- if .DBParadigm}}
  paradigm: "{{.DBParadigm}}"
{{- end}}
{{- if .SchemaPaths}}
  schema_paths:
{{- range .SchemaPaths}}
    - "{{.}}"
{{- end}}
{{- end}}
{{- end}}
`))

// configView is the flattened, slash-normalized data the config template needs.
type configView struct {
	Name, Language, Framework string
	Production, Test, Example []string
	ORM, DBType, DBParadigm   string
	SchemaPaths               []string
}

// RenderConfig renders a commented .codefit.yaml for the detected project. Paths
// are slash-normalized so the committed file is portable across operating systems.
func RenderConfig(info ProjectInfo) ([]byte, error) {
	view := configView{
		Name:        info.Name,
		Language:    info.Language,
		Framework:   info.Framework,
		Production:  toSlashAll(info.PathCriticality.Production),
		Test:        toSlashAll(info.PathCriticality.Test),
		Example:     toSlashAll(info.PathCriticality.Example),
		ORM:         info.ORM,
		DBType:      info.DBType,
		DBParadigm:  info.DBParadigm,
		SchemaPaths: toSlashAll(info.SchemaPaths),
	}
	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, view); err != nil {
		return nil, fmt.Errorf("rendering config: %w", err)
	}
	return buf.Bytes(), nil
}

func toSlashAll(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := make([]string, len(in))
	for i, s := range in {
		out[i] = filepath.ToSlash(s)
	}
	return out
}
